### ISSUE TITLE
Add a property to disable the selection of the tool for a criterion

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqa-composer-templates#15]
For some criteria we will not allow the selection of the tool, this shall be marked by a boolean such as `selectable: false` in the :
```yaml
    "QC.Lic": {
        "description": {
            "msg": "Usage of an open license to distribute your code",
            "improves": "external contributions, reusability",
            "docs": "https://indigo-dc.github.io/sqa-baseline/#licensing-qc.lic"
        },
        "tools": {
            "license": ["licensee"]
        },
        selectable: false
    }
```
